version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
